FROM lcr.loongnix.cn/openeuler/openeuler:24.03-LTS-SP3

RUN sed -i '/\[update-source\]/,$d' /etc/yum.repos.d/openEuler.repo 
RUN sed -i "s#openEuler-24.03-LTS-Next/#openEuler-24.03-LTS-SP3/#" /etc/yum.repos.d/openEuler.repo

RUN dnf install -y \
    wget curl which git make automake autoconf libtool m4 \
    python3 python3-devel python3-pip libatomic-static \
    gcc gcc-c++ gcc-gfortran libstdc++-static simde-devel \
    go cmake clang clang-tools-extra xxhash-devel \
    openblas-devel libaio libaio-devel libuuid-devel \
    zlib-devel openssl-devel boost-devel ccache zip unzip \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install jinja2==3.1.3

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | \
      sh -s -- -y --default-toolchain nightly
ENV PATH=/root/.cargo/bin:$PATH

CMD ["/bin/bash"]
